services:
  cinemate-db:
    container_name: cinemate
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - cinemate-network
    restart: unless-stopped

networks:
  cinemate-network:
    driver: bridge

volumes:
  db:
