#server:
#  port: 5000

cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/cinemate_db
    username: postgres
    password: admin123
  flyway:
    baseline-on-migrate: true
    schemas: cinemate_db
  jpa:
    hibernate:
        ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: cinemate_db

  main:
    web-application-type: servlet
