#server:
#  port: 5000

cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/cinemate_db
    username: postgres
    password: admin123
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
        ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  main:
    web-application-type: servlet
